spring:
  datasource:
    initialize: true
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
    sql-script-encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        web-allow-others: false
